apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: appNN
  name: appNN-subscription
  namespace: appNN
spec:
  channel: hrokejgithubio-showgitops-ns/hrokejgithubio-showgitops
  name: helm-chart-appMM
  packageOverrides:
  - packageName: helm-chart-appMM
    packageAlias: helm-chart-appMM
  placement:
    placementRef:
      kind: PlacementRule
      name: appNN-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: appNN
  name: appNN-placement
  namespace: appNN
spec:
  clusterSelector:
    matchLabels:
      'name': 'phil-managed'
---
