apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: app1
  name: app1-subscription-1
  namespace: app1
spec:
  channel: hrokejgithubio-showgitops-ns/hrokejgithubio-showgitops
  name: helm-chart-app1
  packageOverrides:
  - packageName: helm-chart-app1
    packageAlias: helm-chart-app1
  placement:
    placementRef:
      kind: PlacementRule
      name: app1-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: app1
  name: app1-placement-1
  namespace: app1
spec:
  clusterSelector:
    matchLabels:
      'name': 'phil-managed'