apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-app-appsub
  namespace: openshift-gitops
spec:
  destination:
    namespace: blueargoapp-appsub
    server: 'https://kubernetes.default.svc'
  source:
    path: sub1
    repoURL: https://github.com/rokej/testrepo.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default