apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: red-app-appset
  namespace: openshift-gitops
spec:
  destination:
    namespace: redargoapp-appset
    server: 'https://kubernetes.default.svc'
  source:
    path: resource
    repoURL: https://github.com/rokej/testrepo.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default