apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-argo-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: blueargoapp
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/rokej/BlueApplications.git
    targetRevision: main
    path: kioskApplication
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default